# Generated by Django 5.2.7 on 2026-05-06 05:11

import creatorscribe_api.models.upload_models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('full_name', models.CharField(blank=True, max_length=60, null=True)),
                ('email', models.EmailField(help_text='Email address used for login', max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('phone_number', models.CharField(blank=True, help_text='Phone number (optional)', max_length=20, null=True)),
                ('username', models.CharField(help_text='Auto-generated from email address', max_length=150, unique=True)),
                ('profile_pic', models.ImageField(blank=True, help_text='User profile picture', null=True, upload_to='profile_pics/')),
                ('oauth_provider', models.CharField(blank=True, help_text='OAuth provider (e.g., google, facebook, github)', max_length=50, null=True)),
                ('oauth_id', models.CharField(blank=True, help_text='Unique ID from OAuth provider', max_length=255, null=True, unique=True)),
                ('oauth_access_token', models.TextField(blank=True, help_text='OAuth access token (encrypted in production)', null=True)),
                ('subscription_type', models.CharField(choices=[('free', 'Free'), ('premium_monthly', 'Premium Monthly'), ('premium_yearly', 'Premium Yearly')], default='free', help_text='User subscription plan', max_length=20)),
                ('subscription_start_date', models.DateTimeField(blank=True, help_text='When the current subscription started', null=True)),
                ('subscription_end_date', models.DateTimeField(blank=True, help_text='When the subscription expires (for premium users)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False, help_text='Email verification status')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='CaptionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt', models.TextField(blank=True)),
                ('media_type', models.CharField(choices=[('video', 'Video'), ('image', 'Image'), ('none', 'None')], default='none', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('extracting', 'Extracting Audio'), ('transcribing', 'Transcribing'), ('captioning', 'Generating Captions'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('turn_index', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caption_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'caption_jobs',
                'ordering': ['turn_index'],
            },
        ),
        migrations.CreateModel(
            name='AudioOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='audio/')),
                ('duration', models.FloatField(null=True)),
                ('language', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audio', to='creatorscribe_api.captionjob')),
            ],
            options={
                'db_table': 'caption_audio_outputs',
            },
        ),
        migrations.CreateModel(
            name='CaptionOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('tags', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='caption', to='creatorscribe_api.captionjob')),
            ],
            options={
                'db_table': 'caption_outputs',
            },
        ),
        migrations.CreateModel(
            name='CaptionSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caption_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'caption_sessions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='captionjob',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='creatorscribe_api.captionsession'),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(blank=True, help_text='Name of the client/brand', max_length=255, null=True)),
                ('brand_logo', models.ImageField(blank=True, help_text='Client brand logo', null=True, upload_to='client_logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='User who created and owns this client', on_delete=django.db.models.deletion.CASCADE, related_name='owned_clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'db_table': 'clients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='captionsession',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caption_sessions', to='creatorscribe_api.client'),
        ),
        migrations.AddField(
            model_name='captionjob',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caption_jobs', to='creatorscribe_api.client'),
        ),
        migrations.CreateModel(
            name='ClientMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('editor', 'Editor'), ('viewer', 'Viewer')], default='viewer', help_text='Permission level for this member', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', help_text='Whether the invite has been accepted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(help_text='Client this membership belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='creatorscribe_api.client')),
                ('invited_by', models.ForeignKey(help_text='User who sent the invite', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invites', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='Invited user', on_delete=django.db.models.deletion.CASCADE, related_name='client_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Member',
                'verbose_name_plural': 'Client Members',
                'db_table': 'client_members',
            },
        ),
        migrations.CreateModel(
            name='CreditUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text='Optional description of the action', null=True)),
                ('token_count', models.PositiveIntegerField(default=1, help_text='Number of tokens consumed by this action')),
                ('used_at', models.DateTimeField(auto_now_add=True, help_text='When the credit was used')),
                ('user', models.ForeignKey(help_text='User who used the credit', on_delete=django.db.models.deletion.CASCADE, related_name='credit_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credit Usage',
                'verbose_name_plural': 'Credit Usages',
                'ordering': ['-used_at'],
            },
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(max_length=6)),
                ('otp_type', models.CharField(choices=[('registration', 'Registration'), ('signin', 'Sign In'), ('password_reset', 'Password Reset')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OTP Verification',
                'verbose_name_plural': 'OTP Verifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('youtube', 'YouTube'), ('instagram', 'Instagram'), ('facebook', 'Facebook (Meta)'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter / X')], help_text='Social media platform', max_length=20)),
                ('account_name', models.CharField(help_text='Display name or handle of the account', max_length=255)),
                ('access_token', models.TextField(help_text='OAuth access token')),
                ('refresh_token', models.TextField(blank=True, help_text='OAuth refresh token', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When the access token expires', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(help_text='Client this social account belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to='creatorscribe_api.client')),
            ],
            options={
                'verbose_name': 'Social Account',
                'verbose_name_plural': 'Social Accounts',
                'db_table': 'social_accounts',
            },
        ),
        migrations.CreateModel(
            name='TranscriptionOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_text', models.TextField()),
                ('language', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcription', to='creatorscribe_api.captionjob')),
            ],
            options={
                'db_table': 'caption_transcription_outputs',
            },
        ),
        migrations.CreateModel(
            name='TranscriptionSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('start_second', models.FloatField()),
                ('end_second', models.FloatField()),
                ('index', models.PositiveIntegerField()),
                ('transcription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='creatorscribe_api.transcriptionoutput')),
            ],
            options={
                'db_table': 'caption_transcription_segments',
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=creatorscribe_api.models.upload_models.upload_file_path)),
                ('file_type', models.CharField(max_length=100)),
                ('size', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads', to='creatorscribe_api.client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='captionjob',
            name='uploaded_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caption_jobs', to='creatorscribe_api.uploadedfile'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['owner', 'client_name'], name='clients_owner_i_c6469b_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['-created_at'], name='clients_created_cf1920_idx'),
        ),
        migrations.AddIndex(
            model_name='captionsession',
            index=models.Index(fields=['client', '-updated_at'], name='caption_ses_client__0a98b6_idx'),
        ),
        migrations.AddIndex(
            model_name='captionsession',
            index=models.Index(fields=['user', '-updated_at'], name='caption_ses_user_id_d36eef_idx'),
        ),
        migrations.AddIndex(
            model_name='clientmember',
            index=models.Index(fields=['client', 'status'], name='client_memb_client__b10eff_idx'),
        ),
        migrations.AddIndex(
            model_name='clientmember',
            index=models.Index(fields=['user', 'status'], name='client_memb_user_id_13f669_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='clientmember',
            unique_together={('client', 'user')},
        ),
        migrations.AddIndex(
            model_name='creditusage',
            index=models.Index(fields=['user', '-used_at'], name='creatorscri_user_id_351e40_idx'),
        ),
        migrations.AddIndex(
            model_name='socialaccount',
            index=models.Index(fields=['client', 'platform'], name='social_acco_client__e34950_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='socialaccount',
            unique_together={('client', 'platform')},
        ),
        migrations.AddIndex(
            model_name='captionjob',
            index=models.Index(fields=['client', '-created_at'], name='caption_job_client__e5387a_idx'),
        ),
        migrations.AddIndex(
            model_name='captionjob',
            index=models.Index(fields=['session', 'turn_index'], name='caption_job_session_ed5071_idx'),
        ),
    ]
