# Generated by Django 5.2.7 on 2025-11-01 18:09

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('full_name', models.CharField(max_length=60)),
                ('email', models.EmailField(help_text='Email address used for login', max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('phone_number', models.CharField(blank=True, help_text='Phone number (optional)', max_length=20, null=True)),
                ('username', models.CharField(help_text='Auto-generated from email address', max_length=150, unique=True)),
                ('profile_pic', models.ImageField(blank=True, help_text='User profile picture', null=True, upload_to='profile_pics/')),
                ('oauth_provider', models.CharField(blank=True, help_text='OAuth provider (e.g., google, facebook, github)', max_length=50, null=True)),
                ('oauth_id', models.CharField(blank=True, help_text='Unique ID from OAuth provider', max_length=255, null=True, unique=True)),
                ('oauth_access_token', models.TextField(blank=True, help_text='OAuth access token (encrypted in production)', null=True)),
                ('subscription_type', models.CharField(choices=[('free', 'Free'), ('premium_monthly', 'Premium Monthly'), ('premium_yearly', 'Premium Yearly')], default='free', help_text='User subscription plan', max_length=20)),
                ('subscription_start_date', models.DateTimeField(blank=True, help_text='When the current subscription started', null=True)),
                ('subscription_end_date', models.DateTimeField(blank=True, help_text='When the subscription expires (for premium users)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False, help_text='Email verification status')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(help_text='Name of the client/brand', max_length=255)),
                ('brand_logo', models.ImageField(blank=True, help_text='Client brand logo', null=True, upload_to='client_logos/')),
                ('industry_type', models.CharField(choices=[('technology', 'Technology'), ('healthcare', 'Healthcare'), ('finance', 'Finance'), ('retail', 'Retail'), ('education', 'Education'), ('hospitality', 'Hospitality'), ('real_estate', 'Real Estate'), ('entertainment', 'Entertainment'), ('food_beverage', 'Food & Beverage'), ('fashion', 'Fashion'), ('automotive', 'Automotive'), ('manufacturing', 'Manufacturing'), ('consulting', 'Consulting'), ('marketing', 'Marketing'), ('other', 'Other')], default='other', help_text='Industry type of the client', max_length=50)),
                ('contact_person', models.CharField(help_text='Primary contact person name', max_length=255)),
                ('contact_email', models.EmailField(help_text='Contact email address', max_length=254)),
                ('contact_phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20, null=True)),
                ('facebook_url', models.URLField(blank=True, help_text='Facebook profile/page URL', max_length=500, null=True)),
                ('instagram_url', models.URLField(blank=True, help_text='Instagram profile URL', max_length=500, null=True)),
                ('youtube_url', models.URLField(blank=True, help_text='YouTube channel URL', max_length=500, null=True)),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn profile/company page URL', max_length=500, null=True)),
                ('twitter_url', models.URLField(blank=True, help_text='Twitter/X profile URL', max_length=500, null=True)),
                ('tiktok_url', models.URLField(blank=True, help_text='TikTok profile URL', max_length=500, null=True)),
                ('preferred_post_time', models.TimeField(blank=True, help_text='Preferred time for posting content (HH:MM format)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when client was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when client was last updated')),
                ('user', models.ForeignKey(help_text='User who owns this client account', on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'db_table': 'clients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('transcription', 'Transcription'), ('audio_conversion', 'Audio Conversion'), ('video_processing', 'Video Processing'), ('general', 'General')], default='general', help_text='Type of action that consumed the credit', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Optional description of the action', null=True)),
                ('used_at', models.DateTimeField(auto_now_add=True, help_text='When the credit was used')),
                ('user', models.ForeignKey(help_text='User who used the credit', on_delete=django.db.models.deletion.CASCADE, related_name='credit_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credit Usage',
                'verbose_name_plural': 'Credit Usages',
                'ordering': ['-used_at'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the job', unique=True)),
                ('file_type', models.CharField(choices=[('audio', 'Audio'), ('video', 'Video'), ('image', 'Image')], help_text='Type of file being processed', max_length=10)),
                ('original_filename', models.CharField(help_text='Original name of the uploaded file', max_length=255)),
                ('file_path', models.CharField(help_text='Path to the uploaded file', max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Current status of the job', max_length=20)),
                ('converted_audio_path', models.CharField(blank=True, help_text='Path to converted audio file (for video processing)', max_length=500, null=True)),
                ('caption_length', models.CharField(default='medium', help_text='Caption length: short, medium, or long', max_length=10)),
                ('description_length', models.CharField(default='medium', help_text='Description length: short, medium, or long', max_length=10)),
                ('hashtag_count', models.IntegerField(default=15, help_text='Number of hashtags to generate')),
                ('result_data', models.JSONField(blank=True, help_text='Generated content (caption, description, hashtags, etc.)', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if job failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the job was created')),
                ('started_at', models.DateTimeField(blank=True, help_text='When the job processing started', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the job was completed or failed', null=True)),
                ('client', models.ForeignKey(help_text='Client/brand this job is for', on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='hero_one_api.client')),
                ('user', models.ForeignKey(help_text='User who created the job', on_delete=django.db.models.deletion.CASCADE, related_name='user_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(max_length=6)),
                ('otp_type', models.CharField(choices=[('registration', 'Registration'), ('signin', 'Sign In'), ('password_reset', 'Password Reset')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OTP Verification',
                'verbose_name_plural': 'OTP Verifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['user', 'client_name'], name='clients_user_id_fe4fee_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['industry_type'], name='clients_industr_f9c8a6_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['-created_at'], name='clients_created_cf1920_idx'),
        ),
        migrations.AddIndex(
            model_name='creditusage',
            index=models.Index(fields=['user', '-used_at'], name='hero_one_ap_user_id_a6d057_idx'),
        ),
        migrations.AddIndex(
            model_name='creditusage',
            index=models.Index(fields=['user', 'action_type'], name='hero_one_ap_user_id_8154ed_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['user', '-created_at'], name='hero_one_ap_user_id_c85cf6_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', '-created_at'], name='hero_one_ap_status_5a8d60_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['job_id'], name='hero_one_ap_job_id_50c787_idx'),
        ),
    ]
