# Generated by Django 5.2.7 on 2025-10-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero_one_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='oauth_access_token',
            field=models.TextField(blank=True, help_text='OAuth access token (encrypted in production)', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='oauth_id',
            field=models.CharField(blank=True, help_text='Unique ID from OAuth provider', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='oauth_provider',
            field=models.CharField(blank=True, help_text='OAuth provider (e.g., google, facebook, github)', max_length=50, null=True),
        ),
    ]
