# Generated by Django 5.2.7 on 2025-11-02 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero_one_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='progress',
            field=models.IntegerField(default=0, help_text='Processing progress (0-100)'),
        ),
    ]
