# Generated by Django 5.2.7 on 2025-10-24 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero_one_api', '0002_user_oauth_access_token_user_oauth_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(help_text='Name of the client/brand', max_length=255)),
                ('brand_logo', models.ImageField(blank=True, help_text='Client brand logo', null=True, upload_to='client_logos/')),
                ('industry_type', models.CharField(choices=[('technology', 'Technology'), ('healthcare', 'Healthcare'), ('finance', 'Finance'), ('retail', 'Retail'), ('education', 'Education'), ('hospitality', 'Hospitality'), ('real_estate', 'Real Estate'), ('entertainment', 'Entertainment'), ('food_beverage', 'Food & Beverage'), ('fashion', 'Fashion'), ('automotive', 'Automotive'), ('manufacturing', 'Manufacturing'), ('consulting', 'Consulting'), ('marketing', 'Marketing'), ('other', 'Other')], default='other', help_text='Industry type of the client', max_length=50)),
                ('contact_person', models.CharField(help_text='Primary contact person name', max_length=255)),
                ('contact_email', models.EmailField(help_text='Contact email address', max_length=254)),
                ('contact_phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20, null=True)),
                ('facebook_url', models.URLField(blank=True, help_text='Facebook profile/page URL', max_length=500, null=True)),
                ('instagram_url', models.URLField(blank=True, help_text='Instagram profile URL', max_length=500, null=True)),
                ('youtube_url', models.URLField(blank=True, help_text='YouTube channel URL', max_length=500, null=True)),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn profile/company page URL', max_length=500, null=True)),
                ('twitter_url', models.URLField(blank=True, help_text='Twitter/X profile URL', max_length=500, null=True)),
                ('tiktok_url', models.URLField(blank=True, help_text='TikTok profile URL', max_length=500, null=True)),
                ('preferred_post_time', models.TimeField(blank=True, help_text='Preferred time for posting content (HH:MM format)', null=True)),
                ('language_preference', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('it', 'Italian'), ('pt', 'Portuguese'), ('zh', 'Chinese'), ('ja', 'Japanese'), ('ko', 'Korean'), ('ar', 'Arabic'), ('hi', 'Hindi'), ('ru', 'Russian')], default='en', help_text='Preferred language for content', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when client was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when client was last updated')),
                ('user', models.ForeignKey(help_text='User who owns this client account', on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'db_table': 'clients',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'client_name'], name='clients_user_id_fe4fee_idx'), models.Index(fields=['industry_type'], name='clients_industr_f9c8a6_idx'), models.Index(fields=['-created_at'], name='clients_created_cf1920_idx')],
            },
        ),
    ]
