# Generated by Django 5.2.7 on 2025-11-02 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero_one_api', '0002_job_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Current status of the job', max_length=20),
        ),
    ]
