# Generated by Django 5.2.7 on 2025-10-24 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hero_one_api', '0003_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='language_preference',
        ),
    ]
