# Generated by Django 5.2.7 on 2025-11-01 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero_one_api', '0004_remove_client_language_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription_end_date',
            field=models.DateTimeField(blank=True, help_text='When the subscription expires (for premium users)', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_start_date',
            field=models.DateTimeField(blank=True, help_text='When the current subscription started', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_type',
            field=models.CharField(choices=[('free', 'Free'), ('premium', 'Premium')], default='free', help_text='User subscription plan', max_length=20),
        ),
        migrations.CreateModel(
            name='CreditUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('transcription', 'Transcription'), ('audio_conversion', 'Audio Conversion'), ('video_processing', 'Video Processing'), ('general', 'General')], default='general', help_text='Type of action that consumed the credit', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Optional description of the action', null=True)),
                ('used_at', models.DateTimeField(auto_now_add=True, help_text='When the credit was used')),
                ('user', models.ForeignKey(help_text='User who used the credit', on_delete=django.db.models.deletion.CASCADE, related_name='credit_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credit Usage',
                'verbose_name_plural': 'Credit Usages',
                'ordering': ['-used_at'],
                'indexes': [models.Index(fields=['user', '-used_at'], name='hero_one_ap_user_id_a6d057_idx'), models.Index(fields=['user', 'action_type'], name='hero_one_ap_user_id_8154ed_idx')],
            },
        ),
    ]
